=== benazk/ProyectoMIIB/xml-xsd/ReservasRestaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" xml:long="es">
    <xs:element name="reservaRestaurante">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Reserva" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NombreC">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{1}[a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ApellidoC">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{1}[a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Correo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Telefono">
                                <xs:simpleType>
                                <xs:restriction base="xs:string">   
                                        <xs:pattern value="(\+34|0034|34)?[ -]*(6|7)[ -]*([0-9][ -]*){8}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DiayHora" type="xs:dateTime" />
                            <xs:element name="tipoMenu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Pescado + postre" />
                                        <xs:enumeration value="Marisco + postre" />
                                        <xs:enumeration value="Carne + postre" />
                                        <xs:enumeration value="Pollo + postre" />
                                        <xs:enumeration value="Sopa + postre" />
                                        <xs:enumeration value="Ensalada + postre" />
                                        <xs:enumeration value="Menu Vegano" />
                                        <xs:enumeration value="Menu Proteinico" />
                                        <xs:enumeration value="Legumbres + postre" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== benazk/ProyectoMIIB/xml-xsd/ReservasRestaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservaRestaurante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ReservasRestaurante.xsd">
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
    <Reserva>        
        <NombreC>Benat</NombreC>
        <ApellidoC>Ezquerro</ApellidoC>
        <Correo>bezquerro@gmail.com</Correo>
        <Telefono>+34666555222</Telefono>
        <DiayHora>2024-02-18T11:30:00</DiayHora>
        <tipoMenu>Menu Proteinico</tipoMenu>
    </Reserva>
</reservaRestaurante>
