=== benazk/ProyectoMIIB/xml-xsd/ReservasHotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" xml:long="es">
    <xs:element name="reservaHotel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="inscripcion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                        <xs:pattern value="[A-Z][a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                        <xs:pattern value="[A-Z][a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha" type="xs:date"/>
                            <xs:element name="integrantesCant">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                        <xs:maxInclusive value="4"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="DNI" type="dniType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="dniType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[A-Z]{1}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== benazk/ProyectoMIIB/xml-xsd/ReservasHotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservaHotel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ReservasHotel.xsd">
    <inscripcion DNI="12345678X">
        <nombre>Manuel</nombre>
        <apellido>Garcia</apellido>
        <fecha>2024-12-10</fecha>
        <integrantesCant>2</integrantesCant>
        <email>Nuevo.Email@gmail.com</email>
        <telefono>658992210</telefono>
    </inscripcion>
</reservaHotel>
